/**
 * Self-hosts the two families the design uses (DESIGN.md §2). Google's CSS
 * splits each family across subsets with disjoint unicode-ranges; taking one
 * file silently loses most of basic latin, so every subset listed here is
 * downloaded and re-declared with its own range.
 *
 * Usage: node scripts/prepare-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const FAMILIES = [
  { name: "Mate", slug: "mate", query: "family=Mate", weight: "400" },
  {
    name: "Inter",
    slug: "inter",
    query: "family=Inter:wght@400..500",
    weight: "400 500",
  },
];

const KEEP = new Set(["latin", "latin-ext"]);

const outDir = join(process.cwd(), "public", "fonts");
await mkdir(outDir, { recursive: true });

const blocks = [
  "/* Self-hosted so no third-party request is made at runtime.",
  " * Generated by scripts/prepare-fonts.mjs — do not edit by hand. */",
  "",
];

for (const family of FAMILIES) {
  const css = await fetch(
    `https://fonts.googleapis.com/css2?${family.query}&display=swap`,
    { headers: { "User-Agent": UA } },
  ).then((r) => r.text());

  // Google emits `/* subset */ @font-face { ... }` blocks in order.
  const faces = [...css.matchAll(/\/\*\s*([\w-[\]]+)\s*\*\/\s*@font-face\s*{([^}]+)}/g)];
  let kept = 0;

  for (const [, subset, body] of faces) {
    if (!KEEP.has(subset)) continue;
    const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!url || !range) continue;

    const file = `${family.slug}-${subset}.woff2`;
    const bytes = Buffer.from(
      await fetch(url).then((r) => r.arrayBuffer()),
    );
    await writeFile(join(outDir, file), bytes);
    kept += 1;

    blocks.push(
      "@font-face {",
      `  font-family: "${family.name}";`,
      "  font-style: normal;",
      `  font-weight: ${family.weight};`,
      "  font-display: swap;",
      `  src: url("/fonts/${file}") format("woff2");`,
      `  unicode-range: ${range.trim()};`,
      "}",
      "",
    );
    console.log(`ok  ${file}  ${(bytes.length / 1024).toFixed(1)} KB`);
  }

  if (!kept) throw new Error(`No subsets kept for ${family.name}`);
}

await writeFile(join(process.cwd(), "src", "styles", "fonts.css"), blocks.join("\n"));
console.log("\nwrote src/styles/fonts.css");
